spring:
  application:
    name: acessibilidade-api

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/acessibilidade_db}
    username: ${SPRING_DATASOURCE_USERNAME:acessibilidade_user}
    password: ${SPRING_DATASOURCE_PASSWORD:acessibilidade_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:chave-super-secreta-do-hackathon-com-mais-de-32-caracteres}
  expiration-minutes: ${JWT_EXPIRATION_MINUTES:480}

app:
  cors:
    allowed-origin: ${APP_CORS_ALLOWED_ORIGIN:http://localhost:4200}
    allowed-origin-patterns: ${APP_CORS_ALLOWED_ORIGIN_PATTERNS:http://localhost:4200,http://127.0.0.1:4200,chrome-extension://*,moz-extension://*,edge-extension://*}
